### ISSUE TITLE
Basic example for KotlinJvm and midi device handling

### ISSUE THREAD

**Issue by cansik** [atsushieno/ktmidi#21]
Thank you very much for creating this library. I tried to use it in my current project but it seems that just from the documentation and test scripts, I am not able to get it up and running.

I would like to control some parameters in my software with a midi controller. But I am not able to receive a midi message from my controller:

```kotlin
private val midi = JvmMidiAccess()
private var midiInput: MidiInput? = null

fun main(args: Array) {
    checkForInput()
}

fun checkForInput() {
    for (input in midi.inputs) {
        if (input.name == deviceName) {
            midiInput?.close()
            setupInput(input)
            break
        }
    }
}

fun setupInput(portDetails: MidiPortDetails) {
    midiInput = runBlocking { midi.openInputAsync(portDetails.id) }
    midiInput?.setMessageReceivedListener(this)
}

override fun onEventReceived(data: ByteArray, start: Int, length: Int, timestampInNanoseconds: Long) {
    println("message received")
}
```

Instead of `JvmMidiAccess` I also tried `RtMidiAccess`. A device is found and I can open the port (`openInputAsync`), but I never receive an event. Could you please give me a hint how to receive basic midi data (and maybe even parse it)?

**Comment by atsushieno** [comment]
Hi, thanks for trying out ktmidi! Your code should be alright, but I guess there is some missing bits in my input dispatcher implementation. I haven't touched the native access stack for a while, and now even I cannot get `RtMidiAccess` working on my fresh Ubuntu environment (my use of native access was mostly via AlsaMidiAccess). I'll fist get things working locally and post here back. Sorry for inconvenience!

**Comment by atsushieno** [comment]
I believe I could reproduce the issue, and fixed in 3bc17ff. It was an object pinning issue that I didn't retain the input callback lambda (which is a Java object) that is to be garbage collected, so it could happen to any MIDI driver.

When I was testing, I was quick, maybe too quick, to confirm that the MIDI inputs are received down to ktmidi (I confirmed that those events are dropped when I wait for a while and GC is most probably invoked).

rtmidi binding itself had no issue, but I noticed that while those native libraries are bundled within its jar, they were never loaded as I expect. It is an issue with JNAerator that I use for rtmidi-jna, but it is an unmaintained project so I so far gave up and expect app developers and/or users to ensure that they set up rtmidi by their own responsibility. I updated rtmidi-jna README to state that.

Thanks again for the report! I will bump the version and a new maven package will appear shortly.

**Comment by cansik** [comment]
Thank you very much! Maybe it would make sense to switch to [JavaCPP](https://github.com/bytedeco/javacpp), which is really a good toolkit to create Java-Native-Bindings. There are also already a lot of examples in the [javacpp-presets](https://github.com/bytedeco/javacpp-presets) repository and I work with it for some time now.

Maybe I can have a look at the binding later this month too.

**Comment by atsushieno** [comment]
Yeah JavaCPP is cool, I actually used it in [alsakt](https://github.com/atsushieno/alsakt). In fact I tried JavaCPP for rtmidi first, but it was not successful for whatever reason I don't remember... If you could get your rtmidi preset working and it looks feasible then I would happily switch to the implementation.
